// Regenerates docs/roadmap.md from ROADMAP.md, so the site never drifts from the checklist.
// Usage (from the repository root): node tools/sync-roadmap.js
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const source = fs.readFileSync(path.join(root, "ROADMAP.md"), "utf8").replace(/\r\n/g, "\n");

const repoUrl = "{{ site.github.repository_url }}";
const body = source
    // The page title comes from the front matter.
    .replace(/^# .*\n+/, "")
    .replace(
        /^`docs\/roadmap\.md` is a copy of this file\..*$/m,
        `This page is generated from [\`ROADMAP.md\`](${repoUrl}/blob/dauntless-revived/ROADMAP.md), the checklist we work from.`
    )
    .trimEnd();

// Everything is literal text to Liquid, whatever braces the checklist contains, except the one repository link.
const literal = "{% raw %}\n" + body.split(repoUrl).join(`{% endraw %}${repoUrl}{% raw %}`) + "\n{% endraw %}";

// Search and social description (keep it 120-160 characters) and the language keys the docs use to pair
// English and Finnish pages (lang + ref, see docs/_includes/head_custom.html).
const description =
    "The Dauntless Revived roadmap: what already works, and milestones M0 to M4, from a safety net and playing together to saved progression and the full game loop.";

const page = [
    "---",
    "title: Roadmap",
    "nav_order: 4",
    `description: ${JSON.stringify(description)}`,
    "lang: en",
    "ref: roadmap",
    "---",
    "",
    "<!-- Generated by tools/sync-roadmap.js from ROADMAP.md. Edit ROADMAP.md, then rerun the script. -->",
    "",
    "# Roadmap",
    "{: .no_toc }",
    "",
    "<details open markdown=\"block\">",
    "  <summary>Contents</summary>",
    "  {: .text-delta }",
    "1. TOC",
    "{:toc}",
    "</details>",
    "",
    literal,
    "",
].join("\n");

fs.writeFileSync(path.join(root, "docs", "roadmap.md"), page);
console.log(`docs/roadmap.md regenerated (${page.split("\n").length} lines)`);
