#!/bin/ksh
daemon="@NODE@"
daemon_flags="--env-file=@CONFIG@/deployserver.env @ROOT@/UndauntedDeployServer/dist/server.js"
daemon_user="@USER@"
daemon_logger="daemon.info"
rc_bg=YES

. /etc/rc.d/rc.subr
rc_cmd $1
